Annotations/.NETFramework/mscorlib/4.0.0.0.Contracts.xml
`null` is valid and returns `false`, see http://referencesource.microsoft.com/#mscorlib/system/io/directory.cs,6a2a3bee6b62826f
`               if (path == null)
return false;
if (path.Length == 0)
return false;
`
=> System.IO.Directory.Exists(System.String) NotNull -> CanBeNull

Annotations/Misc/NUnit.Framework/Attributes.xml
Added `CombiningStrategyAttribute`, `DataPointAttribute` and `DataPointSourceAttribute` with `MeansImplicitUse`. These are used by, or are base attributes for, theory tests in nunit
/cc @derigel
=> Added Theory and DataPoint attributes to nunit

Annotations/.NETFramework/mscorlib/Nullness.Manual.xml
=> Add nullness annotations for Object.Equals() and IEquatable<T>.Equals()

Annotations/.NETFramework/mscorlib/ContractAnnotations.xml
Path.GetDirectoryName("C:/") returns "null"
=> Fix annotation for Path.GetDirectoryName

Annotations/.NETFramework/mscorlib/2.0.0.0.Contracts.xml, Annotations/.NETFramework/mscorlib/2.0.5.0.Contracts.xml, Annotations/.NETFramework/mscorlib/4.0.0.0.Contracts.xml
[RSRP-463823](https://youtrack.jetbrains.com/issue/RSRP-463823):  System.Type.GetProperties(flags) can return  null
=> System.Type.GetProperties, System.Type.GetProperty can return null

Annotations/.NETCore/System.Xml.XDocument/4.0.0.0.Nullness.xml
[RSRP-438204](https://youtrack.jetbrains.com/issue/RSRP-438204) CanBeNull annotation for XElement.Attribute
=> CanBeNull attribute for XElement.Attribute

Annotations/.NETFramework/mscorlib/2.0.0.0.Contracts.xml, Annotations/.NETFramework/mscorlib/2.0.5.0.Contracts.xml, Annotations/.NETFramework/mscorlib/4.0.0.0.Contracts.xml
Make "NotNull" attribute for System.Type.GetProperties(BindingFlags). Details: #66
=> 	NotNull for System.Type.GetProperties(BindingFlags)

Annotations/Misc/xUnit.net/xunit.core.xml
Looks like it was simply copy&pasted from non-async `Exception()` method
=> Wrong async method annotation

Annotations/.NETCore/System.Runtime/Attributes.xml
Missing annotations for `String.Format` and `StringBuilder.AppendFormat` overloads. 
The annotations were previously incorrectly put into System.Private.CoreLib and weren't available for ReSharper.
Fixes https://youtrack.jetbrains.com/issue/RSRP-469464, https://youtrack.jetbrains.com/issue/RSRP-467852
=> Missing string format annotations for .NetCore

Annotations/.NETCore/System.Linq.Expressions/Attributes.xml, Annotations/.NETCore/System.Linq/Attributes.xml, Annotations/.NETFramework/System.Core/Annotations.xml, Annotations/.NETStandard/netstandard/Annotations.xml
Fix https://youtrack.jetbrains.com/issue/RSRP-466710
https://docs.microsoft.com/en-us/dotnet/api/system.linq.expressions.expression.makeunary?view=netframework-4.7.2
=> MakeUnary accepts null value in 'type' parmaeter

Annotations/Misc/Caliburn.Micro/Attributes.xml
fixes #149 
I tested this set of annotations locally against Caliburn.Micro 3.2.0, and the Set method appeared correctly:
=> added Caliburn.Micro Set method annotation

Annotations/.NETFramework/System.Web.Http/Annotations.xml
Add [CollectionAccess(CollectionAccessType.ModifyExistingContent)] attribute to the System.Web.Http.Routing.HttpRouteValueDictionary(object values) constructor to prevent the "Content of collection '...' is never updated" warning, since that constructor will (generally) populate the dictionary with items.
=> HttpRouteValueDictionary - Fix false positive "Content of collection '...' is never updated" warning

Annotations/.NETCore/Microsoft.Extensions.Hosting.Abstractions/Attributes.xml, Annotations/.NETCore/Microsoft.Extensions.Options/Attributes.xml
Added `MeansImplicitUse` annotations for more `IServiceCollection` extension methods
- Microsoft.Extensions.Hosting.Abstractions
- `IServiceCollection.AddHostedService<THostedService>`
- Microsoft.Extensions.Options
- `IServiceCollection.AddOptions<TOptions>`
=> Add more Microsoft.Extensions annotations

Annotations/Microsoft/Microsoft.Extensions.Logging.Abstractions/Annotations.xml
Adds the ```StringFormatMethodAttribute``` definitions from [robv8r/resharper-annotations](https://github.com/robv8r/resharper-annotations/blob/master/src/annotations/dotnet/Microsoft.Extensions.Logging.Abstractions/1.0.0.0.Attributes.xml) but without the version attribute, as the affected methods & parameters are the same (so far) across all versions of ```Microsoft.Extensions.Logging.Abstractions```.
The only catch I've noticed is that ReSharper prefers numbered arguments (eg: ```{0}```) over named arguments (eg: ```{value}```), where the logging abstractions support both. However, the ```StringFormatMethodAttribute``` doesn't have any available properties to change this behaviour, and the additional syntax highlighting is better than not having any.
=> Add Microsoft.Extensions.Logging.Abstractions annotations

Annotations/.NETFramework/mscorlib/Annotations.xml
StringBuilder's Replace(string,string) is perfectly content with a null for the newValue parameter.
=> The newValue of a StringBuilder.Replace can be null

Annotations/.NETCore/System.Private.CoreLib/Attributes.xml, Annotations/.NETCore/System.Runtime/Annotations.xml, Annotations/.NETFramework/mscorlib/Annotations.xml, Annotations/.NETStandard/netstandard/Annotations.xml
According to the official doc: https://docs.microsoft.com/en-us/dotnet/api/system.activator.createinstance
For all overloads of the `Activator.CreateInstance()` method, the `string assemblyName` parameter can be `null`.
> If `assemblyName` is `null`, the executing assembly is searched.
This is true for all versions (.NET 5, .NET Core, .NET Framework).
----
Source code also says so:
https://github.com/dotnet/runtime/blob/11cd2721a9bb3fe0c21e20979a3e670f61e3507d/src/libraries/System.Private.CoreLib/src/System/Activator.RuntimeType.cs#L120-L123
=> CanBeNull for assemblyName for System.Activator.CreateInstance

Annotations/.NETCore/System.Private.CoreLib/Attributes.xml, Annotations/.NETFramework/mscorlib/Annotations.xml, Annotations/.NETStandard/netstandard/Annotations.xml
- NotNull for input parameter "path"
> Exceptions - ArgumentNullException - path is null
- CanBeNull for return value
> Returns - null if path is the root directory
Reference: https://docs.microsoft.com/en-us/dotnet/api/system.io.directory.getparent
=> Nullable attributes for System.IO.Directory.GetParent

Annotations/.NETCore/Microsoft.Extensions.Configuration.Binder/Attributes.xml
API doc:
https://docs.microsoft.com/en-us/dotnet/api/microsoft.extensions.configuration.configurationbinder.get
Source code:
https://github.com/dotnet/runtime/blob/main/src/libraries/Microsoft.Extensions.Configuration.Binder/src/ConfigurationBinder.cs
=> MeanImplicitUse(WithMembers) for type parameters of ConfigurationBind.Get

Annotations/Misc/Storyteller/Storyteller.xml
In [Storyteller](https://storyteller.github.io/), `Fixture` classes are used to dynamically compose tests (defined in Markdown files).
=> Add UsedImplicitly to Storyteller Fixture

Annotations/.NETCore/System.Runtime/Attributes.xml, Annotations/.NETCore/System.Runtime/I18n.xml, Annotations/.NETCore/System.Runtime/Pure.xml
Apparently, from .NET 5 onwards, the assembly name is changed from `System.Runtime.Extensions.dll` to `System.Runtime.dll`, so all the annotations aren't activated anymore.
For example, `Math.Max(1, 3)` and `Convert.ToBoolean(42)` are not marked `[Pure]` when csproj is targeted to `net5.0` instead of `netcoreapp3.1` (tested in Rider 2021.1.5 and ReSharper 2021.1.5).
You can see the Assembly changed in the docs, for example:
| .NET 5 | .NET Core 3.1 |
| --- | --- |
| https://docs.microsoft.com/en-us/dotnet/api/system.math?view=net-5.0 | https://docs.microsoft.com/en-us/dotnet/api/system.math?view=netcore-3.1 |
| https://docs.microsoft.com/en-us/dotnet/api/system.convert?view=net-5.0 | https://docs.microsoft.com/en-us/dotnet/api/system.convert?view=netcore-3.1 |
| …
=> Copy System.Runtime.Extensions/*.xml to System.Runtime

Annotations/Misc/Dapper/SqlMapper.Async.MeansImplicitUseAttribute.xml, Annotations/Misc/Dapper/SqlMapper.MeansImplicitUseAttribute.xml
This adds `MeansImplicitUse` for some of the most commonly used methods, all belonging to the class `SqlMapper` in [Dapper](https://www.nuget.org/packages/Dapper):
| sync | async |
| --- | --- |
| `Query()` | `QueryAsync()` |
| `QueryFirst()` | `QueryFirstAsync()` |
| `QueryFirstOrDefault()` | `QueryFirstOrDefaultAsync()` |
| `QuerySingle()` | `QuerySingleAsync()` |
| `QuerySingleOrDefault()` | `QuerySingleOrDefaultAsync()` |
| `ExecuteScalar()` | `ExecuteScalarAsync()` |
I tested the XMLs a bit locally in JetBrains Rider 2021.3 EAP 5 Build #RD-213.5281.17. Works fine.
Also, this should fix [RSRP-434975](https://youtrack.jetbrains.com/issue/RSRP-434975).
=> Add MeansImplicitUse for Dapper

Annotations/.NETFramework/mscorlib/Annotations.xml
Remove incorrect [NotNull] annotation from Array.BinarySearch 'value' parameter, fixes RSRP-488379
=> Remove incorrect [NotNull] annotation from Array.BinarySearch 'value' parameter, fixes RSRP-488379

Annotations/Misc/NUnit.Framework/Attributes.xml
1. DatapointsAttribute means implicit used
2. There is not a single mention of DataPointAttribute in the history of nunit project. I guess it was a typo of DatapointAttribute.
=> NUnit annotations for Datapoints

.space.kts
It turns out the parameter keys in Space have to be lowercase.
=> Deploy: fix a key name issue

Annotations/.NETCore/System.Console/Attributes.xml, Annotations/.NETCore/System.Private.CoreLib/Attributes.xml, Annotations/.NETCore/System.Runtime.Extensions/Attributes.xml, Annotations/.NETCore/System.Runtime/Attributes.xml, Annotations/.NETFramework/System/Attributes.xml, Annotations/.NETFramework/mscorlib/Annotations.xml, Annotations/.NETStandard/netstandard/Annotations.xml, Annotations/Misc/xUnit.net/xunit.abstractions.xml, JetBrains.ExternalAnnotations.nuspec
* Remove attribute from `Console`, `Debug` and `TextWriter` method overloads with one parameter. In these cases argument name "format" was used and annotations had no effect.
* Remove annotation from `Xunit.Abstractions.ITestOutputHelper.WriteLine` overload of one string. This changes the behaviour to the actual one, since this overload does not use `string.Format` ([link](https://github.com/xunit/xunit/blob/b09dbc55ebadaf7ce7eca8584e04e4fc44257c25/src/xunit.v3.core/Sdk/Frameworks/TestOutputHelper.cs#L60))
=> Remove irrelevant [StringFormatMethod]

Annotations/Misc/MediatR/MediatR.xml
Adds annotations for [MediatR](https://github.com/jbogard/MediatR), a widely used mediator library.
It marks as implicitly used all implementations of MediatR services implicitly added to the DI with `services.AddMediatR()`.
=> Add MediatR
