JetBrains/ExternalAnnotations

Annotations/.NETFramework/System.ComponentModel.DataAnnotations/4.0.0.0.Nullness.Gen.xml

Added [NotNull] to IValidatableObject.Validate() result and 'validationContext' parameter

---

Annotations/Misc/FakeItEasy/Attributes.xml

Added external annotations for FakeItEasy (special thanks to @blairconrad, ongoing development in https://github.com/blairconrad/FakeItEasy-annotations).

Added external annotations for FakeItEasy

---

Annotations/.NETFramework/System.Xml.Linq/4.0.0.0.Nullness.Gen.xml

... as in "3.5.0.0.Nullness.Gen.xml" (fixes #7)

Added CanBeNullAttribute to XElement.Attribute()

---

Annotations/Misc/DokanNet/Attributes.xml
Annotations/Misc/DokanNet/FormatString.xml

https://github.com/dokan-dev/dokan-dotnet

Add support for DokanNet

---

Annotations/.NETFramework/System.Net.Http/Nullness.Manual.xml

This pull request fixes issue #26

Fixed #26 System.Net.Http not annotated

---

Annotations/.NETFramework/System.Data/Nullness.Manual.xml

This pull request fixes issue #24

Fixed #24 SqlParameterCollection.Add NotNull

---

Annotations/.NETFramework/System/2.0.0.0.Nullness.Gen.xml
Annotations/.NETFramework/System/4.0.0.0.Nullness.Gen.xml

Fixes #37 (check its description).

Fix nullability of 'NameValueCollection.Add()'

---

Annotations/.NETFramework/mscorlib/Nullness.Manual.xml

Add CanBeNullAttribute to 'Nullable.GetUnderlyingType()'

---

Annotations/Microsoft/EntityFramework/Nullness.Manual.xml

Closes #38 (check its description).

Add nullability annotations for `System.Data.Entity.DbSet` and `System.Data.Entity.DbSet<TEntity>`

---

Annotations/.NETFramework/System.Web/ContractAnnotations.xml
Annotations/.NETFramework/System/ContractAnnotations.xml
Annotations/.NETFramework/mscorlib/ContractAnnotations.xml

for methods that can infer result nullability from parameter nullability

Add ContractAnnotation attributes

---

Annotations/.NETFramework/System.Core/2.0.5.0.Contracts.xml
Annotations/.NETFramework/System.Core/3.5.0.0.Contracts.xml
Annotations/.NETFramework/System.Core/4.0.0.0.Contracts.xml
Annotations/.NETFramework/System.Core/4.0.0.0.Nullness.Gen.xml

OfType linq extension ensures [ItemNotNull]

---

Annotations/.NETFramework/mscorlib/Collections.xml

https://youtrack.jetbrains.com/issue/RSRP-463830

set CollectionAccessType.APPEND for List.InsertRange

---

Annotations/.NETFramework/System/2.0.0.0.Nullness.Gen.xml
Annotations/.NETFramework/System/4.0.0.0.Nullness.Gen.xml

Fixes #3 (check its description).

Changed "message" parameters from [NotNull] to [CanBeNull]

---

Annotations/Microsoft/Microsoft.CodeAnalysis/Microsoft.CodeAnalysis.CSharp.xml

Hi guys,
periodically when I fight Roslyn analyzers I stumble upon suprisingly "CanBeNull" properties.
Do you like me to submit chunks like that? That's highly unlikely that I have time to annotate whole libraries, but I'll probably submit more pieces sometime,

Add first chunks of Microsoft.CodeAnalysis.CSharp

---

Annotations/.NETCore/System.Linq/Attributes.xml
Annotations/.NETCore/System.Linq/Pure.xml
Annotations/.NETFramework/System.Core/Annotations.xml
Annotations/.NETFramework/System.Core/LinqTunnel.xml
Annotations/.NETFramework/System.Core/Pure.xml

https://docs.microsoft.com/en-us/dotnet/api/system.linq.enumerable.tohashset

Add System.Linq.Enumerable.ToHashSet annotation

---

Annotations/.NETCore/System.Private.CoreLib/Attributes.xml
Annotations/.NETFramework/mscorlib/Annotations.xml
Annotations/.NETStandard/netstandard/Annotations.xml

https://docs.microsoft.com/en-us/dotnet/api/system.enum.getvalues?view=netframework-4.7.2

System.Enum.GetValues doesn't return null.

---

Annotations/.NETCore/System.IO.FileSystem.DriveInfo/Attributes.xml
Annotations/.NETCore/System.IO.FileSystem.DriveInfo/I18n.xml
Annotations/.NETFramework/mscorlib/I18n.xml
Annotations/.NETStandard/netstandard/Annotations.xml

https://docs.microsoft.com/en-us/dotnet/api/system.io.driveinfo.name?view=netframework-4.7.2

DriveInfo.Name is never null

---

Annotations/.NETCore/System.Private.Xml/Attributes.xml
Annotations/.NETFramework/System.Xml/Annotations.xml
Annotations/.NETStandard/netstandard/Annotations.xml

Relax not null for XmlWriter.WriteAttributeString

---

Annotations/.NETCore/System.Runtime.Extensions/Attributes.xml
Annotations/.NETFramework/mscorlib/Annotations.xml
Annotations/.NETStandard/netstandard/Annotations.xml

https://docs.microsoft.com/en-us/dotnet/api/system.io.stringwriter.tostring?view=netstandard-1.0

StringWriter.ToString doesn't return null.

---

Annotations/.NETFramework/mscorlib/Annotations.xml

Add Driveinfo.Name annotation to .NET Framework.

---

Annotations/Misc/NUnit.Framework/Attributes.xml

Fixes #140 fixes #141, fixes #146

Add NUnit annotations.

---

Annotations/.NETCore/System.Web.HttpUtility/Attributes.xml

Fixes https://github.com/JetBrains/ExternalAnnotations/issues/193

Fix incorrect [NotNull] annotation on HttpUtility.HtmlEncode overloards

---

Annotations/.NETFramework/PresentationFramework/Annotations.xml

Mark parameter of PrepareCellForEdit method with [CanBeNull]

---

Annotations/.NETCore/System.Data.Common/LanguageInjections.xml
Annotations/.NETCore/System.Data.SqlClient/LanguageInjections.xml
Annotations/.NETCore/System.Xml.ReaderWriter/LanguageInjections.xml
Annotations/.NETCore/System.Xml.XDocument/LanguageInjections.xml
Annotations/Microsoft/Microsoft.EntityFrameworkCore.Relational/LanguageInjections.xml
Annotations/Misc/Newtonsoft.Json/LanguageInjections.xml
JetBrains.ExternalAnnotations.nuspec

This PR adds `[LanguageInjection("<lang_name>")]` annotation to some popular .NET APIs.

Add some language injection annotations
